
# =======================
# I2C
# =======================
CONFIG_I2C=y
CONFIG_I2C_INIT_PRIORITY=60
CONFIG_SERIAL=y
CONFIG_CONSOLE=y

# =======================
# UART
# =======================
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=n

# =======================
# C++ Support
# =======================
CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP20=y
